@startuml
hide empty description

state ":analytics" as analytics
state ":api" as api
state ":config" as config
state ":database" as database
state ":jobs" as jobs
state ":models" as models
state ":notifications" as notifications
state ":repositories" as repositories
state ":resources" as resources
state ":ui" as ui
state ":utils" as utils
state ":viewmodels" as viewmodels
state ":widgets" as widgets

[*] --> models
[*] --> resources
[*] --> utils

models : [kotlinx serialization]
models --> config
resources : [moko resources]
resources --> config
utils : [kotlinx serialization]
utils --> config

config : [gmazzo buildConfig]
config --> api
config --> database

api : [kotlinx serialization]
api : [ksp]
api : [ktorfit]
api --> repositories
database : [sqldelight]
database --> repositories

repositories --> viewmodels
repositories --> analytics
repositories --> notifications
repositories --> widgets
repositories --> jobs

viewmodels --> ui
ui --> analytics

ui ---> AndroidApp
ui ---> iOSApp
ui ---> WebApp

@enduml
