@startuml

database "Data Sources" {
    [Session]
    [AppPreferences]
    [MemoryVerseDb]
    [PrayerDb]
    [VerseOfTheDayApi]
    [VerseOfTheDayDb]
}

node "Repository Layer" {
    [AuthRepository]
    [MemoryVerseRepository]
    [NotificationsRepository]
    [PrayerRepository]
    [VerseOfTheDayRepository]
    [Router]
}

node "UI Layer" {
    [HomeViewModel]
    [SettingsViewModel]
}

' Data Sources --> Repositories
' ----------------------------------------------------------------------------------------------------------------------

Session --> AuthRepository
AppPreferences --> AuthRepository

MemoryVerseDb --> MemoryVerseRepository

MemoryVerseRepository --> NotificationsRepository
AppPreferences --> NotificationsRepository

PrayerDb --> PrayerRepository

AppPreferences --> VerseOfTheDayRepository
VerseOfTheDayApi --> VerseOfTheDayRepository
VerseOfTheDayDb --> VerseOfTheDayRepository

' Repositories --> ViewModels
' ----------------------------------------------------------------------------------------------------------------------

VerseOfTheDayRepository ---> HomeViewModel
MemoryVerseRepository ---> HomeViewModel

AuthRepository ---> SettingsViewModel
AppPreferences ---> SettingsViewModel

@enduml
