@startuml
[*] --> router

router --> session
session --> versesRepository
session --> verseOfTheDayRepository

versesRepository --> versesScreen
verseOfTheDayRepository --> verseOfTheDayScreen

router --> versesScreen
router --> verseOfTheDayScreen

@enduml
