environment: "$APP__ENVIRONMENT:dev"
ktor:
  application:
    modules:
      - com.copperleaf.biblebits.ApplicationKt.module
  deployment:
    port: 9001

security:
  jwt:
    issuer: "http://localhost:9080/auth/realms/biblebits"
    jwksUrl: "http://apisix:9080/auth/realms/biblebits/protocol/openid-connect/certs"
    realm: "biblebits"

connections:
  redis:
    redisConnectionString: "redis://:redis@redis/0"
  db:
    driver: "Postgres"
    postgresConnectionString: "jdbc:postgresql://postgres:5432/biblebits?user=postgres&password=postgres"

services:
  cache:
    driver: "Redis"
  db:
    driver: "Postgres"
  blob:
    driver: "Filesystem"
    path: "/blob/uploads"
  pubsub:
    driver: "Redis"
  authorization:
    driver: "OpenFGA"
    host: "http://openfga:8080"

repositories:
  courses:
    driver: "Postgres"
