services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    attach: false
    ports: [ '4567:4567' ]
    command: [ "start-dev", "--import-realm" ]
    volumes: [ './realm.json:/opt/keycloak/data/import/realm.json' ]
    environment:
      KC_DB: 'postgres'
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak?user=postgres&password=postgres"
      KC_REALM_NAME: 'keycloak'
      KEYCLOAK_ADMIN: 'keycloak'
      KEYCLOAK_ADMIN_PASSWORD: 'keycloak'
      KC_HTTP_PORT: 4567
      KC_HTTP_RELATIVE_PATH: '/auth'
    depends_on:
      postgres: { condition: service_healthy }
